import 'package:meta/meta.dart';

import '../common/source.dart';
import '../knowledge/knowledge_source.dart';

enum Severity { error, warning, info }

/// How strongly the evidence supports a conclusion.
///
/// Confidence is derived from the kind of evidence, never invented:
/// - [certain]: literal values in project files or authoritative facts;
/// - [high]: values resolved through variables or generated files;
/// - [medium]: heuristics (for example which JDK Flutter will select);
/// - [low]: weak or indirect signals.
enum Confidence { certain, high, medium, low }

/// The kind of evidence, keeping facts, observations and inferences apart.
enum EvidenceKind {
  /// Read from a project file maintained by developers.
  projectFile,

  /// Read from a file generated by tooling (lockfiles, plugin registries).
  generatedFile,

  /// Observed in the local environment (tool versions, configuration).
  environment,

  /// A documented fact from the knowledge base.
  knowledge,

  /// Derived by Reforge from other evidence.
  inference,
}

@immutable
final class Evidence {
  const Evidence(this.kind, this.description, {this.location, this.source});

  const Evidence.file(this.description, SourceRef this.location)
      : kind = EvidenceKind.projectFile,
        source = null;

  const Evidence.knowledge(this.description, KnowledgeSource this.source)
      : kind = EvidenceKind.knowledge,
        location = null;

  const Evidence.inference(this.description)
      : kind = EvidenceKind.inference,
        location = null,
        source = null;

  final EvidenceKind kind;
  final String description;
  final SourceRef? location;
  final KnowledgeSource? source;

  Map<String, Object?> toJson() => {
        'kind': kind.name,
        'description': description,
        if (location != null) 'location': location!.toJson(),
        if (source != null) 'source': source!.toJson(),
      };
}

/// Something Reforge noticed about a project.
///
/// Every finding answers: what (title/message), why, impact, and what to do,
/// and carries the evidence it was derived from. [code] is stable and may be
/// referenced by documentation, configuration and automation.
@immutable
final class Finding {
  const Finding({
    required this.code,
    required this.severity,
    required this.title,
    required this.message,
    this.why,
    this.impact,
    this.suggestedAction,
    this.confidence = Confidence.certain,
    this.evidence = const [],
    this.relatedRecipes = const [],
    this.project,
  });

  final String code;
  final Severity severity;
  final String title;
  final String message;
  final String? why;
  final String? impact;
  final String? suggestedAction;
  final Confidence confidence;
  final List<Evidence> evidence;
  final List<String> relatedRecipes;

  /// Workspace-relative path of the project the finding belongs to.
  final String? project;

  Finding forProject(String projectPath) => Finding(
        code: code,
        severity: severity,
        title: title,
        message: message,
        why: why,
        impact: impact,
        suggestedAction: suggestedAction,
        confidence: confidence,
        evidence: evidence,
        relatedRecipes: relatedRecipes,
        project: projectPath,
      );

  Map<String, Object?> toJson() => {
        'code': code,
        'severity': severity.name,
        'title': title,
        'message': message,
        if (why != null) 'why': why,
        if (impact != null) 'impact': impact,
        if (suggestedAction != null) 'suggestedAction': suggestedAction,
        'confidence': confidence.name,
        'evidence': [for (final e in evidence) e.toJson()],
        if (relatedRecipes.isNotEmpty) 'relatedRecipes': relatedRecipes,
        if (project != null) 'project': project,
      };
}
