import '../../../common/source.dart';
import '../../../inspection/android_inspector.dart';
import '../../../knowledge/flutter_release.dart';
import '../../../knowledge/knowledge_source.dart';
import '../../../model/android_project.dart';
import '../../../model/declarations.dart';
import '../../../model/finding.dart';
import '../../../parsing/gradle/gradle_lexer.dart';
import '../../../parsing/gradle/gradle_script.dart';
import '../../../parsing/gradle/gradle_semantics.dart';
import '../../../text/text_edit.dart';
import '../../recipe.dart';
import '../../recipe_ids.dart';
import '../recipe_support.dart';

/// `settings.gradle` generated by Flutter 1.12 to 1.17.
const _settingsTemplate112 = r'''
include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}
''';

/// `settings.gradle` generated by Flutter 1.20 to 3.10.
const _settingsTemplate120 = r'''
include ':app'

def localPropertiesFile = new File(rootProject.projectDir, "local.properties")
def properties = new Properties()

assert localPropertiesFile.exists()
localPropertiesFile.withReader("UTF-8") { reader -> properties.load(reader) }

def flutterSdkPath = properties.getProperty("flutter.sdk")
assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
apply from: "$flutterSdkPath/packages/flutter_tools/gradle/app_plugin_loader.gradle"
''';

/// `settings.gradle` generated by Flutter 3.13 (declarative Flutter Gradle
/// plugin, imperative plugin loader).
const _settingsTemplate313 = r'''
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }
    settings.ext.flutterSdkPath = flutterSdkPath()

    includeBuild("${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle")

    plugins {
        id "dev.flutter.flutter-gradle-plugin" version "1.0.0" apply false
    }
}

include ":app"

apply from: "${settings.ext.flutterSdkPath}/packages/flutter_tools/gradle/app_plugin_loader.gradle"
''';

/// The settings header of the official migration guide (and of the Flutter
/// 3.19 to 3.27 templates).
const _pluginManagement = r'''
pluginManagement {
    def flutterSdkPath = {
        def properties = new Properties()
        file("local.properties").withInputStream { properties.load(it) }
        def flutterSdkPath = properties.getProperty("flutter.sdk")
        assert flutterSdkPath != null, "flutter.sdk not set in local.properties"
        return flutterSdkPath
    }()

    includeBuild("$flutterSdkPath/packages/flutter_tools/gradle")

    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
''';

const _appTemplateStatements = r'''
def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}
''';

const _migrationGuide = KnowledgeSource(
  title: "Flutter breaking change: deprecated imperative apply of Flutter's "
      'Gradle plugins',
  url:
      'https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply',
  retrieved: '2026-09-16',
);

const _kotlinPluginIds = {
  'kotlin-android',
  'org.jetbrains.kotlin.android',
  'kotlin-kapt',
  'org.jetbrains.kotlin.kapt',
  'kotlin-parcelize',
  'org.jetbrains.kotlin.plugin.parcelize',
};

const _kotlinStdlibModules = {
  'org.jetbrains.kotlin:kotlin-stdlib',
  'org.jetbrains.kotlin:kotlin-stdlib-jdk7',
  'org.jetbrains.kotlin:kotlin-stdlib-jdk8',
};

final Set<String> _knownSettingsStatements = {
  for (final template in [
    _settingsTemplate112,
    _settingsTemplate120,
    _settingsTemplate313,
  ])
    for (final statement
        in GradleScript.parse('settings.gradle', template).statements)
      if (statement.leadingPath != 'include') statementFingerprint(statement),
};

final Set<String> _knownAppStatements = {
  for (final statement
      in GradleScript.parse('build.gradle', _appTemplateStatements).statements)
    statementFingerprint(statement),
};

/// A plugin moved from `buildscript` classpath to the settings plugins block.
final class _MigratedPlugin {
  const _MigratedPlugin(this.id, this.version, this.classpath);

  final String id;
  final String version;
  final GradleStatement classpath;
}

/// Migrates Groovy build files from the imperative `apply from:` mechanism to
/// the declarative `plugins {}` blocks introduced in Flutter 3.16, following
/// the official migration guide.
final class FlutterGradlePluginDslRecipe extends MigrationRecipe {
  const FlutterGradlePluginDslRecipe();

  @override
  RecipeDescriptor get descriptor => const RecipeDescriptor(
        id: RecipeIds.androidFlutterGradlePluginDsl,
        title: "Apply Flutter's Gradle plugins declaratively",
        summary: 'Replaces `apply from: .../app_plugin_loader.gradle` and '
            '`apply from: .../flutter.gradle` with plugins {} blocks, moves '
            'the Android Gradle Plugin, Kotlin and documented Firebase plugins '
            'from buildscript classpath to settings.gradle, and preserves '
            'custom configuration.',
        category: RecipeCategory.android,
      );

  @override
  RecipeResult evaluate(RecipeContext context) {
    final android = context.project.android;
    if (android == null) {
      return const NotApplicable('The project has no Android host.');
    }
    final application = android.pluginApplication;
    bool imperative(GradlePluginStyle style) =>
        style == GradlePluginStyle.imperative ||
        style == GradlePluginStyle.mixed;
    final settingsImperative = imperative(application.settingsLoader);
    final appImperative = imperative(application.appPlugin);
    if (!settingsImperative && !appImperative) {
      return NotApplicable(application.style == GradlePluginStyle.declarative
          ? "Flutter's Gradle plugins are already applied declaratively."
          : "Flutter's Gradle plugin application was not recognized, so "
              'there is nothing Reforge knows how to migrate.');
    }

    final release = context.target;
    final Necessity necessity;
    switch (release.imperativeGradleApply) {
      case ImperativeGradleApply.removed:
        necessity = Necessity.required;
      case ImperativeGradleApply.deprecated ||
            ImperativeGradleApply.supportedAlongsideDeclarative:
        necessity = Necessity.recommended;
      case ImperativeGradleApply.supported:
        return NotApplicable('Flutter ${release.version} predates the '
            'declarative plugins block (Flutter 3.16).');
    }

    final settings = android.settings;
    final app = android.app?.script;
    final root = android.rootBuild;
    final evidence = <Evidence>[
      if (settingsImperative && settings != null)
        Evidence.file('Imperative plugin loader', SourceRef(settings.path)),
      if (appImperative && app != null)
        Evidence.file('Imperative Flutter Gradle plugin', SourceRef(app.path)),
      Evidence.knowledge(
          'Flutter ${release.version}: imperative apply is '
          '${release.imperativeGradleApply.name}',
          release.gradleApplySource),
      const Evidence.knowledge('Official migration steps', _migrationGuide),
    ];
    const summary = "Apply Flutter's Gradle plugins with plugins {} blocks.";
    const rationale = 'Flutter 3.16 introduced declarative plugins {} blocks, '
        '3.19 deprecated imperative apply and 3.29 removed it.';
    Proposal manual(String reason, [List<String> steps = const []]) => Proposal(
          status: StepStatus.manual,
          necessity: necessity,
          summary: summary,
          rationale: '$rationale $reason',
          evidence: evidence,
          manualSteps: [
            ...steps,
            'Follow ${_migrationGuide.url}.',
          ],
        );

    for (final script in [settings, app, root]) {
      if (script == null) continue;
      if (script.dialect == GradleDialect.kotlin) {
        return manual('${script.path} uses the Kotlin DSL; Reforge migrates '
            'Groovy build files only.');
      }
      if (!script.isReliable) {
        return manual('${script.path} could not be parsed reliably.');
      }
    }
    if (settings == null || app == null) {
      return manual('settings.gradle or app/build.gradle is missing.');
    }

    final agp = android.toolchain.androidGradlePlugin;
    final kotlin = android.toolchain.kotlin;
    if (agp?.version == null) {
      return manual('The Android Gradle Plugin version could not be '
          'determined (${agp?.note ?? 'no declaration found'}).');
    }

    final reviewNotes = <String>[];
    final notes = <String>[];
    final edits = <FileEdit>[];

    // Plugins that move from the root buildscript classpath to settings.
    final migrated = <_MigratedPlugin>[];
    final keptClasspaths = <String>[];
    final classpathBlock = root?.findBlock(['buildscript', 'dependencies']);
    if (root != null && classpathBlock != null) {
      for (final statement in classpathBlock.statements) {
        final notation = parseDependencyNotation(statement);
        if (notation == null || notation.configuration != 'classpath') {
          if (statement.tokens.isNotEmpty &&
              statement.tokens.first.isIdentifier('classpath')) {
            keptClasspaths
                .add(root.source.substring(statement.start, statement.end));
          }
          continue;
        }
        final id = context.knowledge
            .pluginIdForClasspath(notation.module ?? '')
            ?.value;
        if (id == null) {
          keptClasspaths.add(notation.literal.templateText);
          continue;
        }
        final declaration = AndroidInspector.classpathVersion(
            root, notation, android.gradleProperties);
        if (declaration.version == null) {
          return manual('The version of ${notation.module} could not be '
              'determined (${declaration.note ?? declaration.rawText}).');
        }
        migrated.add(_MigratedPlugin(id, '${declaration.version}', statement));
      }
    }
    final migratedIds = {for (final plugin in migrated) plugin.id};

    // Part C: app/build.gradle.
    final appEdits = <TextEdit>[];
    final removedAppStatements = <GradleStatement>{};
    if (appImperative) {
      final result = _migrateApp(app, migratedIds, kotlin != null, reviewNotes);
      if (result == null) {
        return manual('The Flutter Gradle plugin is applied in a way Reforge '
            'does not recognize in ${app.path}.');
      }
      appEdits.addAll(result.edits);
      removedAppStatements.addAll(result.removed);
      if (appEdits.isNotEmpty) edits.add(FileEdit(app.path, appEdits));
    }

    // Part A: settings.gradle.
    if (settingsImperative) {
      if (!migratedIds.contains('com.android.application') &&
          agp!.site != DeclarationSite.settingsPlugins) {
        return manual('The Android Gradle Plugin is not declared in the root '
            'buildscript classpath, so Reforge cannot move it to settings.');
      }
      final pluginLines = <String>[
        'id "dev.flutter.flutter-plugin-loader" version "1.0.0"',
        for (final plugin in migrated)
          'id "${plugin.id}" version "${plugin.version}" apply false',
      ];
      final result = _migrateSettings(settings, pluginLines, reviewNotes);
      if (result == null) {
        return manual('${settings.path} contains a pluginManagement or plugins '
            'block that Reforge does not recognize.');
      }
      edits.add(FileEdit(settings.path, [result]));
    }

    // Part B: root build.gradle.
    if (root != null && migrated.isNotEmpty && settingsImperative) {
      final rootEdits = _migrateRoot(
          root, app, removedAppStatements, migrated, reviewNotes, notes);
      if (rootEdits.isNotEmpty) edits.add(FileEdit(root.path, rootEdits));
    }
    if (keptClasspaths.isNotEmpty) {
      reviewNotes.add('These buildscript classpath entries have no documented '
          'plugin id and stay in ${root!.path}: ${keptClasspaths.join(', ')}. '
          'Plugins they provide keep working with `apply plugin`.');
    }
    if (context.project.pluginRegistry == null &&
        migrated.any((p) => p.id == 'org.jetbrains.kotlin.android')) {
      notes.add('Plugin sources were not available (run flutter pub get), so '
          'Reforge could not check whether plugins read '
          'rootProject.ext.kotlin_version.');
    }

    return Proposal(
      status: reviewNotes.isEmpty ? StepStatus.auto : StepStatus.review,
      necessity: necessity,
      summary: summary,
      rationale: rationale,
      impact: necessity == Necessity.required
          ? 'Android builds fail with "You are applying Flutter\'s main Gradle '
              'plugin imperatively".'
          : 'Builds print a deprecation error, and Flutter 3.29 or newer fails '
              'to build the app.',
      confidence: context.project.pluginRegistry == null &&
              migrated.any((p) => p.id == 'org.jetbrains.kotlin.android')
          ? Confidence.high
          : Confidence.certain,
      evidence: evidence,
      edits: edits,
      notes: [...reviewNotes, ...notes],
      verification: const [
        VerificationCheck.staticAnalysis,
        VerificationCheck.androidBuild,
      ],
      details: {
        'settingsPlugins': [for (final plugin in migrated) plugin.id],
      },
    );
  }

  ({List<TextEdit> edits, Set<GradleStatement> removed})? _migrateApp(
    GradleScript app,
    Set<String> migratedIds,
    bool kotlinDeclared,
    List<String> reviewNotes,
  ) {
    final statements = app.statements;
    final applyFlutter = statements
        .map(parseApplyStatement)
        .whereType<GradleApplyStatement>()
        .where(isImperativeFlutterGradlePlugin)
        .firstOrNull;
    if (applyFlutter == null) return null;

    final removed = <GradleStatement>{applyFlutter.statement};
    final agpIds = <String>[];
    final firebaseIds = <String>[];
    final kotlinIds = <String>[];
    for (final statement in statements) {
      final apply = parseApplyStatement(statement);
      final id = apply?.kind == 'plugin' ? apply!.value?.constantValue : null;
      if (id == null) continue;
      if (id == 'com.android.application') {
        agpIds.add(id);
      } else if (migratedIds.contains(id) &&
          id != 'org.jetbrains.kotlin.android') {
        firebaseIds.add(id);
      } else if (_kotlinPluginIds.contains(id) && kotlinDeclared) {
        kotlinIds.add(id);
      } else {
        continue;
      }
      removed.add(statement);
    }
    if (agpIds.isEmpty) return null;

    // Applies nested in conditions are left alone.
    for (final statement in app.allStatements) {
      if (statements.contains(statement)) continue;
      final apply = parseApplyStatement(statement);
      if (apply != null && apply.kind == 'plugin') {
        reviewNotes.add('A conditional `apply plugin: '
            "'${apply.value?.templateText ?? '?'}'` in ${app.path} "
            '(line ${app.lineIndex.lineOf(statement.start)}) was left unchanged.');
      }
    }

    // The flutterRoot lookup exists only to locate flutter.gradle.
    final flutterRootStatements = statements
        .where((s) => _knownAppStatements.contains(statementFingerprint(s)))
        .toSet();
    if (flutterRootStatements.isNotEmpty &&
        !isReferenced(app, 'flutterRoot',
            excluding: {...flutterRootStatements, applyFlutter.statement})) {
      removed.addAll(flutterRootStatements);
    }

    // kotlin-stdlib dependencies are provided by the Kotlin Gradle plugin and
    // reference $kotlin_version, which the root build file no longer defines.
    final dependencies =
        statements.where((s) => s.isBlockNamed('dependencies'));
    for (final block in dependencies) {
      final children = block.blocks.first.statements;
      final stdlib = children.where((s) {
        final notation = parseDependencyNotation(s);
        return notation != null &&
            _kotlinStdlibModules.contains(notation.module) &&
            notation.versionText == r'$kotlin_version';
      }).toList();
      if (stdlib.isEmpty) continue;
      if (stdlib.length == children.length) {
        removed.add(block);
      } else {
        removed.addAll(stdlib);
      }
    }

    final edits = removeStatements(app, removed);
    final eol = eolOf(app.source);
    final pluginIds = [
      ...agpIds,
      ...firebaseIds,
      ...kotlinIds,
      'dev.flutter.flutter-gradle-plugin',
    ];
    final block = StringBuffer('plugins {$eol');
    for (final id in pluginIds) {
      block.write('    id "$id"$eol');
    }
    block.write('}$eol$eol');
    final first = statements.firstWhere(
        (s) => !removed.contains(s) && !s.isBlockNamed('buildscript'),
        orElse: () => statements.first);
    edits.add(
        TextEdit.insert(leadingCommentStart(app, first), block.toString()));
    return (edits: edits, removed: removed);
  }

  TextEdit? _migrateSettings(GradleScript settings, List<String> pluginLines,
      List<String> reviewNotes) {
    final source = settings.source;
    final eol = eolOf(source);
    final kept = <String>[];
    final keptRanges = <TextRange>[];
    var includesApp = false;
    for (final statement in settings.statements) {
      final fingerprint = statementFingerprint(statement);
      if (_knownSettingsStatements.contains(fingerprint)) continue;
      if (statement.isBlockNamed('pluginManagement') ||
          statement.isBlockNamed('plugins')) {
        return null;
      }
      final range = TextRange.fromBounds(
          leadingCommentStart(settings, statement),
          settings.lineIndex.lineEndIncludingTerminator(
              settings.lineIndex.lineOf(statement.end - 1)));
      keptRanges.add(range);
      final text = range.textOf(source);
      final isInclude = statement.leadingPath == 'include';
      if (isInclude) {
        includesApp = includesApp ||
            statement.tokens.any((t) => t.string?.constantValue == ':app');
      } else {
        reviewNotes.add('Custom statement kept after the plugins block in '
            '${settings.path}: `${source.substring(statement.start, statement.end).split('\n').first}`.');
      }
      kept.add(text.endsWith('\n') ? text : '$text$eol');
    }
    if (!includesApp) kept.add('include ":app"$eol');

    final firstStatement = settings.statements.firstOrNull;
    final headerEnd = firstStatement == null
        ? 0
        : leadingCommentStart(settings, firstStatement);
    final header = source.substring(0, headerEnd);
    final lostComments = [
      for (final comment in settings.comments)
        if (comment.offset >= headerEnd &&
            !keptRanges
                .any((r) => r.offset <= comment.offset && comment.end <= r.end))
          comment.textOf(source).split('\n').first.trim(),
    ];
    if (lostComments.isNotEmpty) {
      reviewNotes.add('Comments next to replaced template code in '
          '${settings.path} were removed: ${lostComments.join(' | ')}');
    }
    final content = StringBuffer()
      ..write(header)
      ..write(LineEnding.detect(source).apply(_pluginManagement))
      ..write(eol)
      ..write('plugins {$eol');
    for (final line in pluginLines) {
      content.write('    $line$eol');
    }
    content
      ..write('}$eol')
      ..write(eol)
      ..writeAll(kept);
    return TextEdit(0, source.length, content.toString());
  }

  List<TextEdit> _migrateRoot(
    GradleScript root,
    GradleScript app,
    Set<GradleStatement> removedAppStatements,
    List<_MigratedPlugin> migrated,
    List<String> reviewNotes,
    List<String> notes,
  ) {
    final buildscript =
        root.statements.where((s) => s.isBlockNamed('buildscript')).firstOrNull;
    if (buildscript == null) return const [];
    final migratedStatements = {for (final p in migrated) p.classpath};
    final children = buildscript.blocks.first.statements;

    var onlyTemplateContent = true;
    for (final child in children) {
      if (child.isBlockNamed('repositories') || child.isBlockNamed('ext')) {
        continue;
      }
      if (child.isBlockNamed('dependencies')) {
        if (child.blocks.first.statements
            .any((s) => !migratedStatements.contains(s))) {
          onlyTemplateContent = false;
        }
        continue;
      }
      if (child.assignmentValue('ext.${child.leadingPath.split('.').last}') !=
              null &&
          child.leadingPath.startsWith('ext.')) {
        continue;
      }
      onlyTemplateContent = false;
    }

    if (!onlyTemplateContent) {
      reviewNotes.add('The buildscript block in ${root.path} contains other '
          'configuration and was kept; only the migrated classpath entries '
          'were removed.');
      final removals = <GradleStatement>{...migratedStatements};
      // Variables that only served the migrated classpath entries.
      final variables = <String>{
        for (final plugin in migrated)
          for (final part
              in parseDependencyNotation(plugin.classpath)!.literal.parts)
            if (part is GradleInterpolation && part.reference != null)
              part.reference!,
      };
      for (final name in variables.toList()..sort()) {
        final definitions = findVariableDefinitions(root, name);
        if (definitions.length != 1) continue;
        final definition = definitions.single;
        final used = isReferenced(root, name,
                excluding: {...migratedStatements, definition.statement}) ||
            isReferenced(app, name, excluding: removedAppStatements);
        if (used) continue;
        removals.add(definition.statement);
        notes.add('Removed "$name" from ${root.path}; it was only used by '
            'the migrated classpath entries.');
      }
      for (final child in children.where((c) => c.isBlockNamed('ext'))) {
        final entries = child.blocks.first.statements;
        if (entries.isNotEmpty && entries.every(removals.contains)) {
          removals
            ..removeAll(entries)
            ..add(child);
        }
      }
      return removeStatements(root, removals);
    }

    // The whole buildscript block goes away. Keep extra properties that are
    // still used elsewhere.
    final keptProperties = <String>[];
    final eol = eolOf(root.source);
    for (final child in children) {
      final names = <String, GradleToken?>{};
      if (child.leadingPath.startsWith('ext.') && child.blocks.isEmpty) {
        final name = child.leadingPath.substring(4);
        final value = child.assignmentValue('ext.$name');
        if (value != null && value.length == 1) names[name] = value.single;
      } else if (child.isBlockNamed('ext')) {
        for (final entry in child.blocks.first.statements) {
          final value =
              entry.head.length == 3 && entry.head[1].isPunctuation('=')
                  ? entry.head[2]
                  : null;
          if (value != null) names[entry.head.first.identifierName] = value;
        }
      }
      for (final entry in names.entries) {
        final usedInApp =
            isReferenced(app, entry.key, excluding: removedAppStatements);
        final usedInRoot =
            isReferenced(root, entry.key, excluding: {buildscript});
        if (!usedInApp && !usedInRoot) continue;
        final value = entry.value;
        if (value == null) continue;
        keptProperties.add('ext.${entry.key} = ${value.text}');
        notes.add('ext.${entry.key} is still used, so it stays defined in '
            '${root.path}.');
      }
    }

    final range = removalRange(root, buildscript.start, buildscript.end);
    final replacement =
        keptProperties.isEmpty ? '' : '${keptProperties.join(eol)}$eol$eol';
    return [TextEdit.replace(range, replacement)];
  }
}

/// Offset of the first comment line directly above [statement] (no blank line
/// in between), or of the statement's own line.
int leadingCommentStart(GradleScript script, GradleStatement statement) {
  final lines = script.lineIndex;
  var line = lines.lineOf(statement.start);
  while (line > 1) {
    final previous = script.source
        .substring(lines.lineStart(line - 1), lines.lineEnd(line - 1))
        .trim();
    if (!previous.startsWith('//')) break;
    line--;
  }
  return lines.lineStart(line);
}

/// Edits removing [statements] (whole lines), merging adjacent statements so
/// blank lines are collapsed once per removed paragraph.
List<TextEdit> removeStatements(
    GradleScript script, Set<GradleStatement> statements) {
  final lines = script.lineIndex;
  final sorted = statements.toList()
    ..sort((a, b) => a.start.compareTo(b.start));
  final groups = <(int, int)>[];
  for (final statement in sorted) {
    final start = statement.start;
    final end = statement.end;
    if (groups.isNotEmpty) {
      final (groupStart, groupEnd) = groups.last;
      final gap = lines.lineOf(start) - lines.lineOf(groupEnd - 1);
      if (gap <= 1) {
        groups[groups.length - 1] = (groupStart, end);
        continue;
      }
    }
    groups.add((start, end));
  }
  final ranges = [for (final (s, e) in groups) removalRange(script, s, e)];
  // Collapsing may make neighbouring ranges touch; merge them.
  final merged = <TextRange>[];
  for (final range in ranges) {
    if (merged.isNotEmpty && range.offset <= merged.last.end) {
      final last = merged.removeLast();
      merged.add(TextRange.fromBounds(
          last.offset, range.end > last.end ? range.end : last.end));
    } else {
      merged.add(range);
    }
  }
  return [
    for (final range in merged) TextEdit.delete(range.offset, range.length)
  ];
}
