import '../../../common/source.dart';
import '../../../knowledge/flutter_release.dart';
import '../../../knowledge/knowledge_base.dart';
import '../../../model/android_project.dart';
import '../../../model/finding.dart';
import '../../../parsing/gradle/gradle_lexer.dart';
import '../../../parsing/properties/properties_file.dart';
import '../../../text/text_edit.dart';
import '../../recipe.dart';
import '../../recipe_ids.dart';

const _jvmArgs = 'org.gradle.jvmargs';
const _jetifier = 'android.enableJetifier';

/// Updates `org.gradle.jvmargs` when it still has a value generated by an
/// older `flutter create` template.
///
/// Flutter raised the Gradle daemon's memory limits in its templates several
/// times (Flutter 3.16, 3.22, 3.24 and 3.29). Projects keep the value they
/// were created with, and newer Android Gradle Plugin versions can run out of
/// memory with it. Only values that match a template exactly are changed:
/// a customized value is a decision of the project.
final class GradleJvmArgsRecipe extends MigrationRecipe {
  const GradleJvmArgsRecipe();

  @override
  RecipeDescriptor get descriptor => const RecipeDescriptor(
        id: RecipeIds.androidGradleJvmArgs,
        title: 'Update the Gradle JVM memory settings',
        summary: 'Replaces an org.gradle.jvmargs value generated by an older '
            'flutter create template with the value the target release '
            'generates. Customized values are left unchanged.',
        category: RecipeCategory.android,
      );

  @override
  RecipeResult evaluate(RecipeContext context) {
    final android = context.project.android;
    if (android == null) {
      return const NotApplicable('The project has no Android host.');
    }
    final properties = android.gradleProperties;
    if (properties == null) {
      return NotApplicable(
          '${android.directory}/gradle.properties does not exist.');
    }
    final release = context.target;
    final targetValue = release.template.gradleProperties[_jvmArgs];
    if (targetValue == null) {
      return NotApplicable(
          'Flutter ${release.version} templates do not set $_jvmArgs.');
    }
    final entry = properties.entry(_jvmArgs);
    if (entry == null) {
      return NotApplicable('${properties.path} does not set $_jvmArgs. '
          'Reforge does not add JVM settings to a project.');
    }
    if (normalizePropertyValue(entry.value) ==
        normalizePropertyValue(targetValue)) {
      return NotApplicable('$_jvmArgs already has the value generated by '
          'Flutter ${release.version}.');
    }
    final generatedBy = context.knowledge
        .releasesWithTemplateGradleProperty(_jvmArgs, entry.value);
    if (generatedBy.isEmpty) {
      return NotApplicable('$_jvmArgs is customized ("${entry.value}"), so '
          'Reforge leaves it unchanged. Flutter ${release.version} generates '
          '"$targetValue".');
    }
    final first = generatedBy.first;
    final last = generatedBy.last;
    if (first.version > release.version) {
      return NotApplicable('$_jvmArgs has the value generated by Flutter '
          '${first.version}, which is newer than the target release.');
    }

    final generatedIn = first == last
        ? 'Flutter ${first.version}'
        : 'Flutter ${first.version} to ${last.version}';
    final fromHeap = _maximumHeap(entry.value);
    final toHeap = _maximumHeap(targetValue);
    return Proposal(
      status: StepStatus.auto,
      necessity: Necessity.recommended,
      summary: 'Update $_jvmArgs to the value generated by Flutter '
          '${release.version}.',
      rationale: '${properties.path} still has the $_jvmArgs value that '
          'flutter create generated in $generatedIn ("${entry.value}"). '
          'Flutter has changed the Gradle memory settings of its template '
          'since then; Flutter ${release.version} generates "$targetValue".',
      impact: 'Android builds keep the memory limits of an older template, '
          'which can be too small for the Android Gradle Plugin versions '
          'used with Flutter ${release.version}; builds then fail with '
          '"Java heap space".',
      evidence: [
        Evidence.file('$_jvmArgs is "${entry.value}"',
            SourceRef(properties.path, line: entry.line)),
        Evidence.knowledge(
            'flutter create generated "${entry.value}" in $generatedIn',
            first.templateGradlePropertiesSource),
        Evidence.knowledge(
            'flutter create in Flutter ${release.version} generates '
            '"$targetValue"',
            release.templateGradlePropertiesSource),
      ],
      edits: [
        FileEdit(properties.path, [
          TextEdit.replace(
              entry.rawValueRange, escapePropertyValue(targetValue)),
        ]),
      ],
      notes: [
        if (fromHeap != null && toHeap != null && fromHeap != toHeap)
          'The maximum heap of the Gradle daemon changes from $fromHeap to '
              '$toHeap. Machines with less memory, such as small CI runners, '
              'may need a lower value.',
      ],
      verification: const [
        VerificationCheck.staticAnalysis,
        VerificationCheck.androidBuild,
      ],
      details: {'from': entry.value, 'to': targetValue},
    );
  }

  /// The `-Xmx` value of JVM arguments, e.g. `1536M`.
  static String? _maximumHeap(String jvmArgs) =>
      RegExp(r'(?:^|\s)-Xmx(\S+)').firstMatch(jvmArgs)?.group(1);
}

/// Removes `android.enableJetifier=true` once the target release no longer
/// enables Jetifier in new projects.
///
/// Jetifier rewrites dependencies built against the Android Support Library
/// to AndroidX on every build. Flutter removed it from its templates in 3.38
/// because Flutter no longer uses the Support Library and Jetifier fails on
/// class files of newer Java versions. Whether a project still needs it
/// depends on Android dependencies Reforge cannot fully see, so the step is
/// always reviewed.
final class JetifierRecipe extends MigrationRecipe {
  const JetifierRecipe();

  @override
  RecipeDescriptor get descriptor => const RecipeDescriptor(
        id: RecipeIds.androidJetifier,
        title: 'Stop running Jetifier',
        summary: 'Removes android.enableJetifier=true when the target Flutter '
            'release no longer enables Jetifier in new projects and the '
            'build scripts use no Android Support Library dependency.',
        category: RecipeCategory.android,
        runsAfter: [RecipeIds.androidGradleJvmArgs],
      );

  @override
  RecipeResult evaluate(RecipeContext context) {
    final android = context.project.android;
    if (android == null) {
      return const NotApplicable('The project has no Android host.');
    }
    final properties = android.gradleProperties;
    final entries = properties?.entries.where((e) => e.key == _jetifier) ??
        const <PropertyEntry>[];
    if (properties == null ||
        properties.entry(_jetifier)?.value.trim() != 'true') {
      return const NotApplicable('Jetifier is not enabled.');
    }
    final release = context.target;
    if (release.template.gradleProperties[_jetifier] == 'true') {
      return NotApplicable('Flutter ${release.version} still enables '
          'Jetifier in new projects.');
    }
    final removedIn = _templateRemoval(context.knowledge, release);
    final entry = properties.entry(_jetifier)!;
    final evidence = [
      Evidence.file(
          '$_jetifier=true', SourceRef(properties.path, line: entry.line)),
      if (removedIn != null)
        Evidence.knowledge(
            'flutter create no longer enables Jetifier from Flutter '
            '${removedIn.version}',
            removedIn.templateGradlePropertiesSource),
      const Evidence.knowledge(
          'Flutter removed Jetifier from its templates because Flutter no '
          'longer uses the Support Library and Jetifier fails on class files '
          'of newer Java versions',
          KnowledgeBase.jetifierTemplateRemovalSource),
      const Evidence.knowledge(
          "Android Studio's Build Analyzer checks whether "
          'android.enableJetifier can be removed',
          KnowledgeBase.buildAnalyzerJetifierSource),
    ];
    const rationale = 'Jetifier rewrites dependencies built against the '
        'Android Support Library to AndroidX on every build. Flutter no longer '
        'enables it in new projects: Flutter does not use the Support Library, '
        'and Jetifier fails on dependencies compiled for newer Java versions.';
    const impact = 'Every Android build keeps rewriting dependencies with '
        'Jetifier, which costs build time and memory, and fails for '
        'dependencies whose class files Jetifier cannot read.';

    final supportLibraries = _supportLibraryDependencies(android);
    if (supportLibraries.isNotEmpty || entries.length > 1) {
      return Proposal(
        status: StepStatus.manual,
        necessity: Necessity.recommended,
        summary: 'Stop using Jetifier after checking dependencies.',
        rationale: rationale,
        impact: impact,
        evidence: [
          ...evidence,
          for (final dependency in supportLibraries)
            Evidence.file(
                'Depends on the Android Support Library: ${dependency.$1}',
                dependency.$2),
        ],
        manualSteps: [
          if (supportLibraries.isNotEmpty)
            'Replace ${supportLibraries.map((d) => d.$1).join(', ')} with '
                'their AndroidX equivalents '
                '(${KnowledgeBase.androidxMigrationSource.url}).',
          if (entries.length > 1)
            '${properties.path} sets $_jetifier ${entries.length} times; '
                'keep a single entry.',
          'Remove $_jetifier=true from ${properties.path} and build the app.',
        ],
      );
    }

    return Proposal(
      status: StepStatus.review,
      necessity: Necessity.recommended,
      summary: 'Remove $_jetifier=true from ${properties.path}.',
      rationale: rationale,
      impact: impact,
      evidence: evidence,
      edits: [
        FileEdit(properties.path, [TextEdit.replace(entry.lineRange, '')]),
      ],
      notes: const [
        'The build scripts declare no Android Support Library dependency, but '
            'Reforge cannot see the Android dependencies of plugins and '
            'libraries. If one still uses the Support Library (android.support '
            'classes), the build or the app fails without Jetifier. Android '
            "Studio's Build Analyzer can check whether Jetifier is still "
            'needed.',
      ],
      verification: const [
        VerificationCheck.staticAnalysis,
        VerificationCheck.androidBuild,
      ],
    );
  }

  /// The first release after [target]'s last Jetifier-enabling template, i.e.
  /// the release that stopped enabling Jetifier.
  static FlutterRelease? _templateRemoval(
      KnowledgeBase knowledge, FlutterRelease target) {
    FlutterRelease? removal;
    for (final release in knowledge.releases) {
      if (release.version > target.version) break;
      final enabled = release.template.gradleProperties[_jetifier] == 'true';
      if (enabled) {
        removal = null;
      } else {
        removal ??= release;
      }
    }
    return removal;
  }

  /// Dependency notations on Android Support Library artifacts
  /// (`com.android.support:*`, `com.android.support.*:*`) in the build
  /// scripts.
  static List<(String, SourceRef)> _supportLibraryDependencies(
      AndroidProject android) {
    final found = <(String, SourceRef)>[];
    for (final script in android.scripts) {
      for (final token in script.tokens) {
        final literal = token.string;
        if (token.kind != GradleTokenKind.string || literal == null) continue;
        final text = literal.templateText;
        if (text.startsWith('com.android.support:') ||
            text.startsWith('com.android.support.')) {
          final parts = text.split(':');
          found.add((
            parts.length >= 2 ? '${parts[0]}:${parts[1]}' : text,
            script.refAt(token.offset),
          ));
        }
      }
    }
    return found;
  }
}
