// Generates lib/src/knowledge/data/toolchain_releases.g.dart: published
// stable versions of Gradle (with distribution checksums), the Android Gradle
// Plugin and the Kotlin Gradle plugin.
//
// Recipes choose target versions only from these lists, so Reforge never
// proposes a version that does not exist.
//
// Sources:
//  * https://services.gradle.org/versions/all
//  * https://services.gradle.org/distributions/gradle-<v>-{bin,all}.zip.sha256
//  * https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/maven-metadata.xml
//  * https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/maven-metadata.xml
//
// Usage: dart run tool/generate_toolchain_releases.dart

import 'dart:convert';
import 'dart:io';

import 'src/generated_file.dart';

final _stable = RegExp(r'^\d+\.\d+(\.\d+)?$');

Future<void> main(List<String> arguments) async {
  final client = HttpClient();
  try {
    Future<String> get(String url) async {
      final request = await client.getUrl(Uri.parse(url));
      request.followRedirects = true;
      final response = await request.close();
      if (response.statusCode != 200) {
        throw StateError('GET $url failed with ${response.statusCode}');
      }
      return response.transform(utf8.decoder).join();
    }

    List<int> numbers(String version) =>
        version.split('.').map(int.parse).toList();
    int compare(String a, String b) {
      final x = numbers(a);
      final y = numbers(b);
      for (var i = 0; i < 3; i++) {
        final left = i < x.length ? x[i] : 0;
        final right = i < y.length ? y[i] : 0;
        if (left != right) return left.compareTo(right);
      }
      return 0;
    }

    // Gradle.
    final gradleJson =
        jsonDecode(await get('https://services.gradle.org/versions/all'))
            as List;
    final gradle = <String>[];
    for (final entry in gradleJson.cast<Map<String, Object?>>()) {
      final version = entry['version']! as String;
      if (entry['snapshot'] == true ||
          entry['nightly'] == true ||
          entry['releaseNightly'] == true ||
          entry['broken'] == true ||
          (entry['rcFor'] as String).isNotEmpty ||
          (entry['milestoneFor'] as String).isNotEmpty ||
          !_stable.hasMatch(version) ||
          numbers(version).first < 7) {
        continue;
      }
      gradle.add(version);
    }
    gradle.sort(compare);
    final gradleRecords = <String>[];
    for (final version in gradle) {
      final bin = (await get(
              'https://services.gradle.org/distributions/gradle-$version-bin.zip.sha256'))
          .trim();
      final all = (await get(
              'https://services.gradle.org/distributions/gradle-$version-all.zip.sha256'))
          .trim();
      gradleRecords
          .add("  GradleReleaseRecord('$version', bin: '$bin', all: '$all'),");
      stdout.write('.');
    }
    stdout.writeln();

    List<String> mavenVersions(String xml, int minimumMajor) {
      final versions = RegExp(r'<version>([^<]+)</version>')
          .allMatches(xml)
          .map((m) => m.group(1)!)
          .where(_stable.hasMatch)
          .where((v) => numbers(v).first >= minimumMajor)
          .toSet()
          .toList()
        ..sort(compare);
      return versions;
    }

    final agp = mavenVersions(
        await get(
            'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/maven-metadata.xml'),
        7);
    final kotlin = mavenVersions(
        await get(
            'https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/maven-metadata.xml'),
        1);

    final out = StringBuffer()
      ..writeln(
          '// GENERATED by tool/generate_toolchain_releases.dart. Do not edit by hand.')
      ..writeln(
          '// Generated on ${DateTime.now().toUtc().toIso8601String().substring(0, 10)}.')
      ..writeln()
      ..writeln("import 'toolchain_release_record.dart';")
      ..writeln()
      ..writeln('/// Date the release lists were generated.')
      ..writeln(
          "const toolchainReleasesGeneratedOn = '${DateTime.now().toUtc().toIso8601String().substring(0, 10)}';")
      ..writeln()
      ..writeln(
          '/// Stable Gradle releases (7.0 and newer) with distribution SHA-256 checksums.')
      ..writeln('const gradleReleases = <GradleReleaseRecord>[')
      ..writeAll(gradleRecords, '\n')
      ..writeln()
      ..writeln('];')
      ..writeln()
      ..writeln('/// Stable Android Gradle Plugin releases (7.0 and newer).')
      ..writeln('const androidGradlePluginReleases = <String>[')
      ..writeAll(agp.map((v) => "  '$v',"), '\n')
      ..writeln()
      ..writeln('];')
      ..writeln()
      ..writeln('/// Stable Kotlin Gradle plugin releases.')
      ..writeln('const kotlinGradlePluginReleases = <String>[')
      ..writeAll(
          kotlin.where((v) => compare(v, '1.5.0') >= 0).map((v) => "  '$v',"),
          '\n')
      ..writeln()
      ..writeln('];');
    const path = 'lib/src/knowledge/data/toolchain_releases.g.dart';
    final written = await writeGeneratedDart(path, out.toString(), volatile: [
      RegExp(r'^// Generated on '),
      RegExp(r'^const toolchainReleasesGeneratedOn = '),
    ]);
    stdout.writeln(
        'Gradle ${gradle.length}, AGP ${agp.length}, Kotlin ${kotlin.length}'
        '${written ? '' : ' (unchanged)'}');
  } finally {
    client.close();
  }
}
