// Generates lib/src/docs/recipe_docs.g.dart from docs/recipes/*.md, so that
// `reforge explain` works offline. Run from packages/reforge:
//
//   dart run tool/generate_recipe_docs.dart
//
// test/recipe_docs_test.dart fails when the generated docs are out of date.

import 'dart:io';

import 'package:path/path.dart' as p;

void main() {
  final docs = Directory(p.join('..', '..', 'docs', 'recipes'));
  final output = p.join('lib', 'src', 'docs', 'recipe_docs.g.dart');
  File(output).writeAsStringSync(renderRecipeDocs(docs));
  Process.runSync('dart', ['format', output]);
  stdout.writeln('Wrote lib/src/docs/recipe_docs.g.dart.');
}

/// The generated Dart source for the recipe documents in [directory].
String renderRecipeDocs(Directory directory) {
  final files = directory
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.md'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/generate_recipe_docs.dart from '
        'docs/recipes. Do not edit.')
    ..writeln()
    ..writeln('/// Recipe documentation by recipe id.')
    ..writeln('const recipeDocs = <String, String>{');
  for (final file in files) {
    final id = p.basenameWithoutExtension(file.path);
    final content = file.readAsStringSync().replaceAll('\r\n', '\n');
    buffer.writeln("  '$id': ${_literal(content)},");
  }
  buffer.writeln('};');
  return buffer.toString();
}

String _literal(String value) {
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n');
  return "'$escaped'";
}
