import 'package:meta/meta.dart';
import 'package:pub_semver/pub_semver.dart';

import '../version/tool_version.dart';
import 'knowledge_source.dart';

/// How a Flutter release treats the legacy imperative application of its
/// Gradle plugins (`apply from: ".../flutter.gradle"`).
enum ImperativeGradleApply {
  /// The only supported mechanism (before Flutter 3.16).
  supported,

  /// Declarative `plugins {}` exists but imperative apply still works
  /// silently (Flutter 3.16).
  supportedAlongsideDeclarative,

  /// Imperative apply works but logs a deprecation error (Flutter 3.19+).
  deprecated,

  /// Imperative apply throws at configuration time (Flutter 3.29+).
  removed,
}

/// The Gradle DSL used by `flutter create` for new apps.
enum GradleDsl { groovy, kotlin }

/// A minimum version enforced by Flutter's Gradle plugin: builds fail below
/// [error] and print a deprecation warning below [warn].
@immutable
final class VersionFloor {
  const VersionFloor({required this.error, required this.warn});

  final ToolVersion error;
  final ToolVersion warn;

  /// The status of [version] relative to this floor.
  FloorStatus statusOf(ToolVersion version) {
    if (version < error) return FloorStatus.belowError;
    if (version < warn) return FloorStatus.belowWarn;
    return FloorStatus.satisfied;
  }
}

enum FloorStatus { belowError, belowWarn, satisfied }

/// Android build requirements enforced by a Flutter release.
@immutable
final class AndroidRequirements {
  const AndroidRequirements({
    required this.gradle,
    required this.androidGradlePlugin,
    required this.kotlin,
    required this.java,
    required this.minSdk,
  });

  /// `null` when the release does not check the version at all (Flutter
  /// releases before 3.22 had no dependency version checker).
  final VersionFloor? gradle;
  final VersionFloor? androidGradlePlugin;
  final VersionFloor? kotlin;

  /// Java major versions (for example `17`).
  final VersionFloor? java;

  /// Android API levels.
  final VersionFloor? minSdk;
}

/// Values generated by `flutter create` for a release. A project using these
/// values matches a combination the Flutter team shipped and tested.
@immutable
final class TemplateToolchain {
  const TemplateToolchain({
    required this.gradle,
    required this.androidGradlePlugin,
    required this.kotlin,
    required this.dsl,
    required this.declarativePlugins,
    required this.namespaceInBuildScript,
    required this.gradleProperties,
    required this.appAppliesKotlinPlugin,
  });

  final ToolVersion gradle;
  final ToolVersion androidGradlePlugin;
  final ToolVersion kotlin;
  final GradleDsl dsl;

  /// Whether new projects apply Flutter's Gradle plugins with `plugins {}`.
  final bool declarativePlugins;

  /// Whether new projects declare `namespace` in `app/build.gradle` (instead
  /// of `package` in `AndroidManifest.xml`).
  final bool namespaceInBuildScript;

  /// The properties new projects get in `android/gradle.properties`.
  final Map<String, String> gradleProperties;

  /// Whether the app module of new projects applies the Kotlin Gradle plugin
  /// (`kotlin-android`) itself.
  final bool appAppliesKotlinPlugin;
}

/// Defaults exposed by the Flutter Gradle plugin as `flutter.compileSdkVersion`
/// and friends.
@immutable
final class FlutterAndroidDefaults {
  const FlutterAndroidDefaults({
    required this.compileSdk,
    required this.targetSdk,
    required this.minSdk,
    required this.ndkVersion,
  });

  final int compileSdk;
  final int targetSdk;
  final int minSdk;
  final String ndkVersion;
}

/// Facts about one stable Flutter release.
@immutable
final class FlutterRelease {
  const FlutterRelease({
    required this.version,
    required this.revision,
    required this.dartVersion,
    required this.releaseDate,
    required this.androidRequirements,
    required this.androidDefaults,
    required this.template,
    required this.imperativeGradleApply,
    required this.iosMinimumDeploymentTarget,
    required this.androidMigrations,
    required this.appliesKotlinPlugin,
  });

  final Version version;

  /// The framework git revision of the release.
  final String revision;

  final Version dartVersion;
  final DateTime releaseDate;
  final AndroidRequirements androidRequirements;
  final FlutterAndroidDefaults androidDefaults;
  final TemplateToolchain template;
  final ImperativeGradleApply imperativeGradleApply;

  /// The minimum iOS deployment target supported by the release.
  final ToolVersion iosMinimumDeploymentTarget;

  /// Class names of the project migrations `flutter build` and `flutter run`
  /// apply to the Android host project before every Gradle build, for
  /// example `DisableNewDslMigration`. They change project files without
  /// asking.
  final List<String> androidMigrations;

  /// Whether Flutter's Gradle plugin applies the Kotlin Gradle plugin to app
  /// and plugin modules that do not apply it themselves, while built-in
  /// Kotlin is disabled (Flutter 3.44+).
  final bool appliesKotlinPlugin;

  /// The source of [appliesKotlinPlugin].
  KnowledgeSource get appliesKotlinPluginSource => sourceFor(
      'packages/flutter_tools/gradle/src/main/kotlin/FlutterPluginUtils.kt');

  /// Whether the Flutter tool of this release runs the Android project
  /// migration [name].
  bool runsAndroidMigration(String name) => androidMigrations.contains(name);

  /// The source of versions, revisions, Dart versions and release dates.
  static const releaseManifestSource = KnowledgeSource(
    title: 'Flutter release manifest',
    url:
        'https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json',
  );

  /// Where facts about this release come from.
  KnowledgeSource sourceFor(String file) => KnowledgeSource(
        title: 'flutter/flutter $version: $file',
        url: 'https://github.com/flutter/flutter/blob/$version/$file',
      );

  /// Flutter's Gradle dependency version checker for this release (the
  /// source of [androidRequirements]).
  KnowledgeSource get dependencyCheckerSource {
    final String file;
    if (version >= Version(3, 32, 0)) {
      file =
          'packages/flutter_tools/gradle/src/main/kotlin/DependencyVersionChecker.kt';
    } else if (version >= Version(3, 29, 0)) {
      file =
          'packages/flutter_tools/gradle/src/main/kotlin_scripts/dependency_version_checker.gradle.kts';
    } else {
      file =
          'packages/flutter_tools/gradle/src/main/kotlin/dependency_version_checker.gradle.kts';
    }
    return sourceFor(file);
  }

  /// The source of [iosMinimumDeploymentTarget].
  KnowledgeSource get iosMinimumSource => sourceFor(version >= Version(3, 7, 0)
      ? 'packages/flutter_tools/lib/src/ios/migrations/ios_deployment_target_migration.dart'
      : 'packages/flutter_tools/lib/src/ios/migrations/deployment_target_migration.dart');

  /// The source of [imperativeGradleApply].
  KnowledgeSource get gradleApplySource =>
      sourceFor('packages/flutter_tools/gradle/flutter.gradle');

  /// The source of [template] and [androidDefaults] versions.
  KnowledgeSource get templateSource =>
      sourceFor('packages/flutter_tools/lib/src/android/gradle_utils.dart');

  /// The source of [androidDefaults] (Flutter's Gradle plugin).
  KnowledgeSource get androidDefaultsSource =>
      sourceFor(version >= Version(3, 32, 0)
          ? 'packages/flutter_tools/gradle/src/main/kotlin/FlutterExtension.kt'
          : version >= Version(3, 13, 0)
              ? 'packages/flutter_tools/gradle/src/main/groovy/flutter.groovy'
              : 'packages/flutter_tools/gradle/flutter.gradle');

  /// Where Flutter's Gradle plugin warns about plugins that compile against a
  /// higher Android SDK than the app.
  KnowledgeSource get pluginCompileSdkCheckSource => sourceFor(version >=
          Version(3, 47, 0)
      ? 'packages/flutter_tools/gradle/src/main/kotlin/tasks/ValidateCompileSdkVersionTask.kt'
      : version >= Version(3, 32, 0)
          ? 'packages/flutter_tools/gradle/src/main/kotlin/FlutterPluginUtils.kt'
          : version >= Version(3, 13, 0)
              ? 'packages/flutter_tools/gradle/src/main/groovy/flutter.groovy'
              : 'packages/flutter_tools/gradle/flutter.gradle');

  /// The source of [androidMigrations].
  KnowledgeSource get androidMigrationsSource =>
      sourceFor('packages/flutter_tools/lib/src/android/gradle.dart');

  /// The implementation of the Android project migration [name], e.g.
  /// `DisableNewDslMigration` in `disable_new_dsl_migration.dart`.
  KnowledgeSource androidMigrationSource(String name) {
    final file = name
        .replaceAllMapped(
            RegExp('(?<=[a-z0-9])(?=[A-Z])|(?<=[a-z])(?=[0-9])'), (_) => '_')
        .toLowerCase();
    return sourceFor(
        'packages/flutter_tools/lib/src/android/migrations/$file.dart');
  }

  /// The source of [TemplateToolchain.gradleProperties].
  KnowledgeSource get templateGradlePropertiesSource => sourceFor(version >=
          Version(3, 29, 0)
      ? 'packages/flutter_tools/templates/app/android.tmpl/gradle.properties.tmpl'
      : 'packages/flutter_tools/templates/app_shared/android.tmpl/gradle.properties.tmpl');

  @override
  String toString() => 'Flutter $version';
}
