import 'package:meta/meta.dart';
import 'package:pub_semver/pub_semver.dart';

import '../environment/environment.dart';
import '../knowledge/flutter_release.dart';
import '../knowledge/knowledge_base.dart';
import '../model/finding.dart';
import '../model/flutter_project.dart';

/// Why Reforge believes a project currently uses a Flutter version.
enum CurrentFlutterBasis {
  /// Pinned with FVM or `.tool-versions`.
  pinned,

  /// The `flutter` executable in the environment.
  environment,

  /// The SDK that last ran `pub get` (generated files).
  lastPubGet,

  /// The SDK that created the project (`.metadata`).
  created,
}

@immutable
final class CurrentFlutterVersion {
  const CurrentFlutterVersion({
    required this.version,
    required this.release,
    required this.basis,
    required this.confidence,
    required this.evidence,
  });

  final Version version;

  /// The facts about [version], or `null` when it is older than the releases
  /// the knowledge base describes.
  final FlutterRelease? release;

  final CurrentFlutterBasis basis;
  final Confidence confidence;
  final Evidence evidence;

  Map<String, Object?> toJson() => {
        'version': '$version',
        'described': release != null,
        'basis': basis.name,
        'confidence': confidence.name,
        'evidence': evidence.toJson(),
      };
}

/// Determines which Flutter release a project currently builds with.
///
/// Pins express the team's intent and win; otherwise the environment's
/// `flutter`, then the SDK recorded by the last `pub get`, then the SDK that
/// created the project. Releases the knowledge base describes are returned
/// with their facts; older stable releases only by version. Newer or unknown
/// versions are skipped.
CurrentFlutterVersion? resolveCurrentFlutterVersion(
  FlutterProject project, {
  Environment? environment,
  required KnowledgeBase knowledge,
}) {
  FlutterRelease? known(Object? version) => version == null
      ? null
      : knowledge.releases.where((r) => r.version == version).firstOrNull;

  final pin = project.pinnedFlutterVersion;
  if (pin != null && known(pin.version) != null) {
    return CurrentFlutterVersion(
      version: pin.version!,
      release: known(pin.version),
      basis: CurrentFlutterBasis.pinned,
      confidence: Confidence.high,
      evidence: Evidence(EvidenceKind.projectFile,
          'Flutter ${pin.value} is pinned in ${pin.location.path}',
          location: pin.location),
    );
  }
  final sdk = environment?.flutter;
  if (sdk?.version != null && known(sdk!.version) != null) {
    return CurrentFlutterVersion(
      version: sdk.version!,
      release: known(sdk.version),
      basis: CurrentFlutterBasis.environment,
      confidence: Confidence.high,
      evidence: Evidence(EvidenceKind.environment,
          '`flutter --version` reports ${sdk.version}'),
    );
  }
  for (final signal in const [
    FlutterVersionSignal.packageConfig,
    FlutterVersionSignal.pluginRegistry,
  ]) {
    final observation = project.flutterVersionObservations
        .where((o) => o.signal == signal && known(o.version) != null)
        .firstOrNull;
    if (observation != null) {
      return CurrentFlutterVersion(
        version: observation.version!,
        release: known(observation.version),
        basis: CurrentFlutterBasis.lastPubGet,
        confidence: Confidence.medium,
        evidence: Evidence(
            EvidenceKind.generatedFile,
            '${observation.location.path} was generated by Flutter '
            '${observation.value}',
            location: observation.location),
      );
    }
  }
  // .metadata also identifies stable releases older than those described.
  final created = project.flutterVersionObservations
      .where((o) =>
          o.signal == FlutterVersionSignal.metadataRevision &&
          o.version != null)
      .firstOrNull;
  if (created != null) {
    return CurrentFlutterVersion(
      version: created.version!,
      release: known(created.version),
      basis: CurrentFlutterBasis.created,
      confidence: Confidence.low,
      evidence: Evidence(
          EvidenceKind.projectFile,
          '.metadata records that the project was created with Flutter '
          '${created.version}',
          location: created.location),
    );
  }
  return null;
}
